apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uw-coursematch
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: uw-coursematch-frontend
            port:
              number: 80
      - path: /api/v1
        pathType: Prefix
        backend:
          service:
            name: uw-coursematch-backend
            port:
              number: 8001
