apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8001
  type: {{ .Values.backend.service.type }}
