# Step 1: Build the Vite app
FROM node:18 AS build

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json (or yarn.lock if you're using Yarn)
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the frontend code
COPY frontend/ ./

# Pass API URL at buildtime instead of hardcoding
ENV VITE_API_URL=http://localhost
ENV VITE_API_PORT=30081

# Build the Vite app
RUN npm run build

# Step 2: Serve the app using a lightweight HTTP server
FROM nginx:alpine

# Copy the built app from the build step into the nginx container
COPY --from=build /app/dist /usr/share/nginx/html

# Expose the port that Nginx will serve on
EXPOSE 80


# Start the Nginx server to serve the static files
CMD ["nginx", "-g", "daemon off;"]
